import Head from 'next/head';
import type { GetStaticProps, InferGetStaticPropsType } from 'next';
import Advertise from '@/components/mainPage/Advertise';
import RecommendBeer from '@/components/smallCards/RecommendBeer';
import BeerCategoryBtn from '@/components/mainPage/BeerCategoryBtn';
import Footer from '@/components/Footer';
import axios from '@/pages/api/axios';
import { useState } from 'react';
import PopularBeer from '@/components/smallCards/PopularBeer';
import { useRecoilState } from 'recoil';
import { accessToken } from '@/atoms/login';
import { useQuery } from '@tanstack/react-query';
import {
  PopularBeerType,
  RecommendBeerType,
} from '@/components/beerPage/BeerDeclare';

// API 호출 함수를 컴포넌트 밖으로 분리
const fetchRecommendBeer = async (token: string) => {
  const config = {
    headers: { Authorization: token, 'Content-Type': 'application/json' },
    withCredentials: true,
  };
  const { data } = await axios.get(`/api/beers/recommend`, config);
  return data;
};

export default function Main({
  weeklyBeer,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const [TOKEN] = useRecoilState<string>(accessToken);
  const [popularBeer, setPopularBeer] = useState<PopularBeerType[] | string>(
    weeklyBeer
  );

  // React Query를 사용하여 사용자 추천 맥주 데이터 페칭
  const { data: recommendBeer, isLoading: isRecommendLoading } = useQuery<
    RecommendBeerType[]
  >({
    queryKey: ['recommendBeer', TOKEN], // Query Key
    queryFn: () => fetchRecommendBeer(TOKEN), // Query Function
    enabled: !!TOKEN, // TOKEN이 있을 때만 쿼리 실행
  });

  return (
    <>
      <Head>
        <title>GetABeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main className="m-auto h-screen max-w-4xl">
        <Advertise />
        <div className="m-auto">
          <BeerCategoryBtn />
          {popularBeer === '' ? (
            <></>
          ) : (
            <>
              <PopularBeer popularBeer={popularBeer} />
            </>
          )}
          {isRecommendLoading ? (
            <div className="m-3 mt-6 text-base font-semibold lg:text-xl">
              추천 맥주를 불러오는 중...
            </div>
          ) : (
            recommendBeer &&
            recommendBeer.length > 0 && (
              <>
                <div className="m-3 mt-6 text-base font-semibold lg:text-xl">
                  <span className="text-black">나를 위한</span>
                  <span className="text-y-brown mr-1">추천 맥주</span>
                </div>
                <RecommendBeer recommendBeer={recommendBeer} />
              </>
            )
          )}
        </div>
        <div className="pb-8"></div>
        <Footer />
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  // async여야 함
  const response = await fetch(`${process.env.API_URL}/api/beers/recommend`);
  const weeklyBeer: PopularBeerType = await response.json();
  return {
    props: {
      weeklyBeer,
    },
  };
};
